### PR TITLE
Add Python 3.7, 3.8, and 3.9 to testing matrix

### LINKED ISSUE #2: ImportError: .../_lltraceback.cpython-38-x86_64-linux-gnu.so: undefined symbol: _PyThreadState_GetFrame
Hello,

I am not sure, if this repository is actively maintained, because the last changes are some time ago.

I tried to use `ptracer` and installed it in a Python 3.8 environment.
The import failed in Python 3.8:
```python
>>> import ptracer
...
ImportError: .../ptracer/_lltraceback.cpython-38-x86_64-linux-gnu.so: undefined symbol: _PyThreadState_GetFrame
```

Then I tried it in an older environment with Python 3.6 on another computer and `ptracer` worked.

I found https://bugs.python.org/issue39946 and from the comments there, it looks like `_PyThreadState_GetFrame` was removed in Python 3.7.

### PR DESCRIPTION
**Pull request by jparise**
Fixes #2

### CODE REVIEW

**Comment by jparise** [comment]
@elprans do you see an alternative that would work for Python 3.7 and 3.8, or should we just remove support for those versions?

**Comment by elprans** [comment]
There should be a way.  I'll need to do a bit of digging.

**Comment by elprans** [comment]
@jparise, turns out vstinner has made a nice compatibility shim over at https://github.com/pythoncapi/pythoncapi_compat/blob/master/pythoncapi_compat.h, which polyfills `PyThreadState_GetFrame` on older Pythons, so we can just pluck that in.

**Comment by elprans** [comment]
> so we can just pluck that in.

Or just copy the relevant piece.

**Comment by jparise** [comment]
@elprans Good stuff. All working now.

**Review by elprans — APPROVED** [review]

**Pull request merged**
